package academy.pocu.comp2500.assignment1.registry;

/**
 * DO NOT MODIFY. YOU DON'T HAVE TO!
 */
public enum InterfaceKey {
    BLOG_CREATOR,
    TAG_FILTER_SETTER,
    AUTHOR_FILTER_SETTER,
    POST_ORDER_SETTER,
    POST_LIST_GETTER,
    POST_ADDER,
    POST_TITLE_UPDATER,
    POST_BODY_UPDATER,
    POST_TAG_ADDER,
    COMMENT_ADDER,
    SUBCOMMENT_ADDER,
    COMMENT_UPDATER,
    REACTION_ADDER,
    REACTION_REMOVER,
    COMMENT_UPVOTER,
    COMMENT_DOWNVOTER,
    COMMENT_LIST_GETTER,
    SUBCOMMENT_LIST_GETTER,
    SUBCOMMENT_UPDATER,
    SUBCOMMENT_UPVOTER,
    SUBCOMMENT_DOWNVOTER
}
